name: Storefront 1000063397

on:
  workflow_call:
    secrets:
      OXYGEN_DEPLOYMENT_TOKEN_1000063397:
        required: true
    outputs: 
      preview_url:
        description: 'The URL of the deployed preview'
        value: ${{ jobs.get_deployment_data.outputs.preview_url }}
      bypass_token:
        description: 'The auth bypass token for the deployed preview'
        value: ${{ jobs.get_deployment_data.outputs.bypass_token }}

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy to Oxygen
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build and Publish to Oxygen
        run: npx shopify hydrogen deploy --auth-bypass-token
        env:
          SHOPIFY_HYDROGEN_DEPLOYMENT_TOKEN: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_1000063397 }}
      
  get_deployment_data:
    name: Get Deployment Data
    needs: deploy
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.get_deployment_data.outputs.preview_url }}
      bypass_token: ${{ steps.get_deployment_data.outputs.bypass_token }}
    steps:
      - name: Get Deployment Data
        id: get_deployment_data
        run: |
          echo "bypass_token=$(jq -r '.authBypassToken' h2_deploy_log.json)" >> $GITHUB_OUTPUT
          echo "preview_url=$(jq -r '.url' h2_deploy_log.json)" >> $GITHUB_OUTPUT
        env:
          SHOPIFY_HYDROGEN_DEPLOYMENT_TOKEN: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_1000063397 }}